name: CI/CD Pipeline - Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Install dependencies
        run: ./mvnw dependency:resolve

      - name: Grant execute permission for build script
        run: chmod +x .github/scripts/build.sh

      - name: Run build script
        run: |
          ./.github/scripts/build.sh
      
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: shipping-service-example-jar
          path: target/shipping-service-example-0.0.1-SNAPSHOT.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: shipping-service-example-jar
          path: ./

      - name: Build Docker image
        run: |
          docker build --build-arg JAR_FILE=shipping-service-example-0.0.1-SNAPSHOT.jar -t ${{ secrets.DOCKER_USERNAME }}/shipping-service-example:dev1 .

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push de imagen Docker
        run: |
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/shipping-service-example:dev1
